import jsPDF from "jspdf";

export function createPDF() {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });
  return doc;
}

export function addHeader(doc, title, subtitle = "") {
  // Header background
  doc.setFillColor(37, 99, 235); // Blue-600
  doc.rect(0, 0, 210, 40, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("GYANSAGAR TEST SYSTEM", 105, 15, { align: "center" });

  // Hindi subtitle
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("ज्ञानसागर कोचिंग क्लासेज", 105, 22, { align: "center" });

  // Page title
  if (subtitle) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(subtitle, 105, 32, { align: "center" });
  }

  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
}

export function addFooter(doc, pageNumber) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(`Page ${pageNumber}`, 105, pageHeight - 10, { align: "center" });
  doc.text("Generated by GyanSagar Test System", 105, pageHeight - 5, { align: "center" });
}

export function addSection(doc, title, y) {
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text(title, 15, y);
  doc.setDrawColor(37, 99, 235);
  doc.line(15, y + 2, 195, y + 2);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  return y + 10;
}

export function addTableRow(doc, data, y, headers = false) {
  const x = 15;
  const colWidths = [15, 60, 30, 30, 30, 30];
  let currentX = x;

  doc.setFontSize(headers ? 10 : 9);
  doc.setFont(headers ? "helvetica" : "helvetica", headers ? "bold" : "normal");

  if (headers) {
    doc.setFillColor(243, 244, 246);
    doc.rect(x, y - 4, 180, 8, "F");
  }

  data.forEach((text, index) => {
    doc.text(String(text || ""), currentX + 2, y);
    currentX += colWidths[index];
  });

  return y + 7;
}

export function checkPageBreak(doc, y, requiredSpace = 20) {
  const pageHeight = doc.internal.pageSize.height;
  if (y + requiredSpace > pageHeight - 20) {
    doc.addPage();
    return 20;
  }
  return y;
}

export function formatDate(date) {
  if (!date) return "-";
  const d = new Date(date);
  return d.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric"
  });
}

export function formatTime(seconds) {
  if (!seconds) return "-";
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}m ${s}s`;
}
