import mongoose from "mongoose";
import { NextResponse } from "next/server";
import Test from "../../../../../models/Test";
import Question from "../../../../../models/Question";
import { connectToDatabase } from "../../../../../lib/mongodb";
import { isObjectId, parseTestInput, requireAdmin } from "../../../../../lib/admin";
const badId = () => NextResponse.json({ success: false, message: "Invalid test id" }, { status: 400 });
export async function GET(_, { params }) { const { id } = await params; try { if (!await requireAdmin()) return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 }); if (!isObjectId(id)) return badId(); await connectToDatabase(); const test = await Test.findById(id).lean(); if (!test) return NextResponse.json({ success: false, message: "Test not found" }, { status: 404 }); return NextResponse.json({ success: true, data: { ...test, questionCount: await Question.countDocuments({ testId: id }) } }); } catch { return NextResponse.json({ success: false, message: "Unable to load test" }, { status: 500 }); } }
export async function PUT(request, { params }) { const { id } = await params; try { if (!await requireAdmin()) return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 }); if (!isObjectId(id)) return badId(); await connectToDatabase(); const test = await Test.findByIdAndUpdate(id, parseTestInput(await request.json()), { new: true, runValidators: true }); if (!test) return NextResponse.json({ success: false, message: "Test not found" }, { status: 404 }); return NextResponse.json({ success: true, data: test }); } catch (error) { return NextResponse.json({ success: false, message: error.message === "Please provide valid test details." ? error.message : "Unable to update test" }, { status: 400 }); } }
export async function DELETE(_, { params }) { const { id } = await params; try { if (!await requireAdmin()) return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 }); if (!isObjectId(id)) return badId(); await connectToDatabase(); const test = await Test.findByIdAndUpdate(id, { isDeleted: true }, { new: true }); if (!test) return NextResponse.json({ success: false, message: "Test not found" }, { status: 404 }); return NextResponse.json({ success: true, message: "Test was deleted" }); } catch (error) { return NextResponse.json({ success: false, message: "Unable to delete test" }, { status: 500 }); } }